export const ADD_REMINDER = 'ADD_REMINDER';
export const DELETE_REMINDER = 'DELETE _REMINDER';
export const CLEAR_REMINDERS = 'CLEAR_REMINDERS';
export const UPDATE_REMINDERS_STATUS = 'UPDATE_REMINDERS_STATUS';